# Generated by Django 5.2.5 on 2025-09-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0002_genre_book_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='minilibrary.book')),
            ],
        ),
    ]
