# Generated by Django 5.2.5 on 2025-09-28 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0006_recomendation_book_recommended_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomendation',
            new_name='Recommendation',
        ),
    ]
