# Generated by Django 5.2.5 on 2025-09-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0007_rename_recomendation_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publication_date',
        ),
    ]
