# Generated by Django 5.2.5 on 2025-09-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0008_rename_published_date_book_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loaned_date',
            new_name='loan_date',
        ),
    ]
