# Generated by Django 5.2.5 on 2025-09-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0009_rename_loaned_date_loan_loan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='returned_date',
            new_name='return_date',
        ),
    ]
